### ISSUE TITLE
copy constructor problem

### ISSUE THREAD

**Issue by jhjensen** [rigtorp/TokenBucket#2]
The copy constructor doesn't initialize time_.  This causes a problem if the memory of the new object  happens to contain a time in the future.  I added the line below, and my problems went away.

TokenBucket(const TokenBucket &other) {
    time_ = other.time_.load(); // added this line
    timePerToken_ = other.timePerToken_.load();
    timePerBurst_ = other.timePerBurst_.load();
  }

**Comment by rigtorp** [comment]
I changed the code to always initialize time to 0. 

Thanks for reporting!
