### ISSUE TITLE
example

### ISSUE THREAD

**Issue by mipac** [rigtorp/TokenBucket#4]
Hi,

I try to use TokenBucket to limit the output rate of an UDP send... and I fail
Could  you give us an example of how to use that class?
If I want to limit at X Mbps an UDP flow @ MTU octets per packet, how can I do?

thanks

**Comment by rigtorp** [comment]
Consume one token per byte. Set max rate to number of bytes per second.

**Comment by mipac** [comment]
Hi, thanks for answer
but what about burst size?

**Comment by rigtorp** [comment]
Set it to at least your max rate. Higher if you want to allow higher
temporary bursts.

**Comment by mipac** [comment]
I tried this:

```
rate = 12500 (ko/s)
bs = 12500 (ko)
TokenBuket t(rate, bs);

if (t.consume(bs)) {
  //send bs octets
} else {
  sleep_for(1ms);
}

```

And I have ~ 700Mo/s with local loop
I missed something ... and I don't find
sorry for repeating the same question... thx for your help ;)

**Comment by rigtorp** [comment]
I assume you are reusing the token bucket instance? It has state that needs
to be preserved between consecutive consume calls.

**Comment by mipac** [comment]
... and it works better with one instance :D

I get an average rate 30% over limit choosen
The µs resolution make the object difficult to use with octect/s directly, would switch to ns make it easier?

**Comment by rigtorp** [comment]
No, but it should be quite easy for you to modify. I will accept a merge
request.

You can also make it sleep the exact amount needed, or return it from the
consume call.

The overhead is probably due to Ethernet + IP + UDP headers. You will need
to take that into account. Depends on how you measure.

**Comment by mipac** [comment]
my mistake... with a correct measure, it's ok 
thanks a lot for help!
