### ISSUE TITLE
Not working as expected ? allowing more tokens .

### ISSUE THREAD

**Issue by vikchopde** [rigtorp/TokenBucket#5]
Hi ,

I am trying your implementation keeping the tokens per sec to 500 . the number of tokens allowed seems to be more than 500 around 512ish ... 
Can you please help me if me going wrong somwher in understanding.

also it does work as expected with smaller token size of say 40 or 100

#include <atomic>
#include <chrono>
#include <iostream>
#include <chrono>
#include <thread>

class TokenBucket {
public:
    TokenBucket() {}

    TokenBucket(const uint64_t rate, const uint64_t burstSize) {
        timePerToken_ = 1000000 / rate;
        timePerBurst_ = burstSize * timePerToken_;
    }

    TokenBucket(const TokenBucket &other) {
        timePerToken_ = other.timePerToken_.load();
        timePerBurst_ = other.timePerBurst_.load();
    }

    TokenBucket &operator=(const TokenBucket &other) {
        timePerToken_ = other.timePerToken_.load();
        timePerBurst_ = other.timePerBurst_.load();
        return *this;
    }

    bool consume(const uint64_t tokens)
    {
        const uint64_t now =
                std::chrono::duration_cast<std::chrono::microseconds>(
                        std::chrono::steady_clock::now().time_since_epoch())
                        .count();
        const uint64_t timeNeeded =
                tokens * timePerToken_.load(std::memory_order_relaxed);
        const uint64_t minTime =
                now - timePerBurst_.load(std::memory_order_relaxed);
        uint64_t oldTime = time_.load(std::memory_order_relaxed);
        uint64_t newTime = oldTime;

        if (minTime > oldTime)
        {
            newTime = minTime;
        }

        for (;;) {
            newTime += timeNeeded;
            if (newTime > now) {
                return false;
            }
            if (time_.compare_exchange_weak(oldTime, newTime,
                                            std::memory_order_relaxed,
                                            std::memory_order_relaxed)) {
                return true;
            }
            newTime = oldTime;
        }

        return false;
    }

private:
    std::atomic<uint64_t> time_ = {0};
    std::atomic<uint64_t> timePerToken_ = {0};
    std::atomic<uint64_t> timePerBurst_ = {0};
};

int main()
{

    uint64_t rate = 500;
    uint64_t bs = 500;
    TokenBucket t(rate, bs);

    uint64_t i{0};
    while(true)
    {
        if (t.consume(1))
        {
            std::cout << ++i << std::endl;
        }
        else
        {
            i = 0;
            std::cout << "cant consume "<< std::endl;
            std::this_thread::sleep_for(std::chrono::seconds(1));
        }
    }
    return 0;
}

Output :
1
2
......
506
507
508
509
510
511
512
513
514
515
516
517
518
cant consume 

Thanks in advance.

**Comment by rigtorp** [comment]
Well this line `std::cout << ++i << std::endl;` will take some non-zero time.
