### ISSUE TITLE
Not considering minTime < oldTime condition if compare_exchange_weak fails

### ISSUE THREAD

**Issue by benstadin** [rigtorp/TokenBucket#7]
Before entering the loop the condition is handled for the case when the previous run (oldTime) is older than the earliest possible bucked (minTime) of the buffer window. 

However, for the case that compare_exchange_weak fails and newTime is reset to oldTime back again and the loop is re-run, setting it to old time is wrong as it does ignore that case?

```
    if (minTime > oldTime) {
      newTime = minTime; // <--- newTime changed
    }

    for (;;) {
      newTime += timeNeeded;
      if (newTime > now) {
        return false;
      }
      if (time_.compare_exchange_weak(oldTime, newTime,
                                      std::memory_order_relaxed,
                                      std::memory_order_relaxed)) {
        return true;
      }
      newTime = oldTime; // <-- newTime reset to oldTime, not considering the eventually required shift to minTime
    }
```

**Comment by rigtorp** [comment]
Yes, you're right. Take a look at the latest version in master, it fixes this problem!
